apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwardensecrets.tomjo.net
  namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
  group: tomjo.net
#  conversion:
#    strategy: Webhook
#    webhook:
#      conversionReviewVersions:
#        - v1
#      clientConfig:
#        service:
#          namespace: bitwarden-operator
#          name: bitwarden-operator-webhook
#          path: /crdconvert
  names:
    kind: BitwardenSecret
    plural: bitwardensecrets
    singular: bitwardensecret
    shortNames:
      - bitwardensecret
      - bw
  scope: Namespaced
  versions:
    - name: v2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                item:
                  type: string
              required: ["item"]
            status:
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                startTime:
                  type: string
                  format: date-time
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        description: Last time the condition transit from one status
                          to another.
                        format: date-time
                        type: string
                      message:
                        description: Human-readable message indicating details about
                          last transition.
                        type: string
                      reason:
                        description: Human-readable message indicating details about
                          any error that occurred.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of job condition, Completed.
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
              type: object
