apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwardensecrets.tomjo.net
  namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
  group: tomjo.net
  names:
    kind: BitwardenSecret
    plural: bitwardensecrets
    singular: bitwardensecret
    shortNames:
      - bitwardensecret
      - bw
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                item:
                  type: string
              required: ["item"]